# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-
# stub: bio-ucsc-util 0.1.3 ruby lib
# stub: ext/ucsc-util/mkrf_conf.rb

Gem::Specification.new do |s|
  s.name = "bio-ucsc-util".freeze
  s.version = "0.1.3"

  s.required_rubygems_version = Gem::Requirement.new(">= 0".freeze) if s.respond_to? :required_rubygems_version=
  s.require_paths = ["lib".freeze]
  s.authors = ["throwern".freeze]
  s.date = "2021-07-02"
  s.description = "Ruby FFI binding of the ucsc kent src. Implemented utilities include: bigWigInfo, bigWigSummary, wigToBigWig, bedToBigBed and bigBedIntervalQuery".freeze
  s.email = "throwern@msu.edu".freeze
  s.extensions = ["ext/ucsc-util/mkrf_conf.rb".freeze]
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.rdoc"
  ]
  s.files = [
    ".document",
    ".ruby-gemset",
    ".ruby-version",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE.txt",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "bio-ucsc-util.gemspec",
    "ext/ucsc-util/README",
    "ext/ucsc-util/makefile",
    "ext/ucsc-util/mkrf_conf.rb",
    "ext/ucsc-util/ucsc-util-src-v268.tgz",
    "lib/bio-ucsc-util.rb",
    "lib/bio/ucsc/big_bed.rb",
    "lib/bio/ucsc/big_wig.rb",
    "lib/bio/ucsc/binding.rb",
    "lib/bio/ucsc/library.rb",
    "lib/bio/ucsc/src/Version",
    "lib/bio/ucsc/util.rb",
    "test/1.bed",
    "test/1.bigbed",
    "test/1.bw",
    "test/1.wig",
    "test/1_smoothed.bw",
    "test/chrom.sizes",
    "test/helper.rb",
    "test/test_big_bed.rb",
    "test/test_big_wig.rb"
  ]
  s.homepage = "http://github.com/throwern/bio-ucsc-util".freeze
  s.licenses = ["MIT".freeze]
  s.rubygems_version = "3.0.9".freeze
  s.summary = "Ruby binding to the ucsc kent utilities for bigWig and bigBed file formats".freeze

  if s.respond_to? :specification_version then
    s.specification_version = 4

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<ffi>.freeze, ["~> 1.9"])
      s.add_development_dependency(%q<rdoc>.freeze, [">= 0"])
      s.add_development_dependency(%q<bundler>.freeze, [">= 2.2.10"])
      s.add_development_dependency(%q<jeweler>.freeze, ["~> 2.1.0"])
    else
      s.add_dependency(%q<ffi>.freeze, ["~> 1.9"])
      s.add_dependency(%q<rdoc>.freeze, [">= 0"])
      s.add_dependency(%q<bundler>.freeze, [">= 2.2.10"])
      s.add_dependency(%q<jeweler>.freeze, ["~> 2.1.0"])
    end
  else
    s.add_dependency(%q<ffi>.freeze, ["~> 1.9"])
    s.add_dependency(%q<rdoc>.freeze, [">= 0"])
    s.add_dependency(%q<bundler>.freeze, [">= 2.2.10"])
    s.add_dependency(%q<jeweler>.freeze, ["~> 2.1.0"])
  end
end

