# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "bio-ucsc-util"
  s.version = "0.1.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["throwern"]
  s.date = "2012-08-07"
  s.description = "Ruby FFI binding and implmentation of the ucsc utilities: bigWigInfo, bigWigSummary and wigToBigWig"
  s.email = "throwern@msu.edu"
  s.extensions = ["ext/ucsc-util/mkrf_conf.rb"]
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.rdoc"
  ]
  s.files = [
    ".document",
    ".rvmrc",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE.txt",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "ext/ucsc-util/README",
    "ext/ucsc-util/makefile",
    "ext/ucsc-util/mkrf_conf.rb",
    "ext/ucsc-util/ucsc-util-src-v268.tgz",
    "lib/bio-ucsc-util.rb",
    "lib/bio/ucsc/big_wig.rb",
    "lib/bio/ucsc/binding.rb",
    "lib/bio/ucsc/library.rb",
    "lib/bio/ucsc/src/Version",
    "lib/bio/ucsc/util.rb",
    "test/1.bed",
    "test/1.bw",
    "test/1.wig",
    "test/1_smoothed.bw",
    "test/chrom.sizes",
    "test/helper.rb",
    "test/test_big_wig.rb"
  ]
  s.homepage = "http://github.com/throwern/bio-ucsc-util"
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.24"
  s.summary = "Ruby binding to the ucsc kent utilities"

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<ffi>, [">= 0"])
      s.add_development_dependency(%q<rdoc>, ["~> 3.12"])
      s.add_development_dependency(%q<bundler>, ["~> 1.0"])
      s.add_development_dependency(%q<jeweler>, ["~> 1.8.3"])
    else
      s.add_dependency(%q<ffi>, [">= 0"])
      s.add_dependency(%q<rdoc>, ["~> 3.12"])
      s.add_dependency(%q<bundler>, ["~> 1.0"])
      s.add_dependency(%q<jeweler>, ["~> 1.8.3"])
    end
  else
    s.add_dependency(%q<ffi>, [">= 0"])
    s.add_dependency(%q<rdoc>, ["~> 3.12"])
    s.add_dependency(%q<bundler>, ["~> 1.0"])
    s.add_dependency(%q<jeweler>, ["~> 1.8.3"])
  end
end

